<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8" />
  <title>Dashboard - Emissor NF</title>
  <link rel="stylesheet" href="/static/css/app.css" />
</head>
<body>
  <div class="main-container">
    <h1 class="page-title">Sistema Emissor de Notas Fiscais</h1>
    <p class="page-subtitle">Escolha uma das opções abaixo para começar:</p>

    <div class="dashboard-grid">
      <a href="/clients" class="dashboard-btn">Clientes</a>
      <a href="/products" class="dashboard-btn">Produtos</a>
      <a href="/invoices" class="dashboard-btn"> Nova Nota Fiscal</a>
      <a href="/invoices/list" class="dashboard-btn">Notas Fiscais</a>
    </div>
  </div>
</body>
</html>
